name: GitHub-Profile-3D-Contrib

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate 3D contribution profile
        uses: yoshi389111/github-profile-3d-contrib@0.2.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: mhqn03
      - name: Commit & Push
        run: |
          git config user.name mhqn03
          git config user.email qanah03@gmail.com
          git add -A .
          git commit -m "generated"
          git push
